import { ClerkProvider, Show, SignInButton, SignUpButton, UserButton } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import Provider from "./provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body
      className="font-sans">
        
        <ClerkProvider>
          
          <header style={{ display: 'flex', justifyContent: 'flex-end', padding: '1rem' }}>
            <Show when="signed-out">
              <SignInButton>
                <button>Sign In</button>
              </SignInButton>
              <SignUpButton>
                <button>Sign Up</button>
              </SignUpButton>
            </Show>
            <Show when="signed-in">
              <UserButton />
            </Show>
          </header>
    <Provider>
   {children}

      </Provider>
           
        
        </ClerkProvider>
      </body>
    </html>
  );
}